### PR TITLE
[PR] Implement a common footer throughout the theme

### PR DESCRIPTION
**Pull request by jeremyfelt**
Adds the footer introduced in #129.

### CODE REVIEW

**Comment by jeremyfelt** [comment]
Tagged both @slocker3 and @philcable for review as I made some adjustments to the markup in the footer.

@slocker - Checkout the common-footer.html style guide to see what things look like when no nav menu is assigned. The SVG goes completely to the right. Not sure how we want to address that.

**Comment by slocker3** [comment]
It all looks great to me. Submitted code to handle the no-nav scenario for the Insider mark.
`margin-left: auto` to `.card--mark`

**Comment by slocker3** [comment]
I agree that it looks funny on posts. I wonder if we should move the category content into the white. It would probably be good to bring in a designer. :)

**Comment by slocker** [comment]
Looks f**n great you guys. Great job, take the rest of the week off.

**Pull request merged**
