### PR TITLE
[PR] Introduce an initial iteration of the category page layout

### PR DESCRIPTION
**Pull request by jeremyfelt**

### CODE REVIEW

**Comment by jeremyfelt** [comment]
We can merge this after shipping the MailChimp fixes, then adjust styles/markup as needed.

**Comment by jeremyfelt** [comment]
Once this gets merged it will be shipped to production in the next release, so I'm going to wait a minute.

I reused content syndicate HTML so that the styles apply pretty quickly. See https://github.com/washingtonstateuniversity/news.wsu.edu-internal/blob/a5e72ac8f1e0467b92832e1290cecf55f1a980fc/style-guide/category.html#L76-L95

If it makes sense, we can use different class names for "content cards" and then apply that to our content syndicate HTML as well.

@slocker3 How does the HTML in the style guide look as a starting spot?

**Comment by slocker3** [comment]
👍  this is a good starting spot

**Comment by jeremyfelt** [comment]
It was borked a bit - too many wrappers. I'm going to go ahead and merge so that style work can start right away tomorrow.

**Pull request merged**
